# Site
repository: czhroailsky/jesus_reyes.github.io
# favicon: images/favicon.ico

# Personal info
name: Jesús Reyes
title: M. S. in Computer Engineering
email: javier.reyes.ic@gmail.com
website: https://czhroailsky.github.io/jesus_reyes.github.io/

# Social links
#twitter_username: facespics
github_username:  czhroailsky
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: czochraiski
linkedin_username: jesús-javier-reyes-torres
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Jesús and I am an enthusiastic about machine learning, natural language processing, probability and reinforcement learning. I completed my Master's in Computer Engineering at the Computer Research Center of the National Polytechnic Institute, México.

  I am most skilled in: <mark>Python programming language</mark>.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my academics interests some of my other interests and hobbies are:
   - Hiking
   - Uncharted (PSN: )
   - Drawing

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
